language: minimal
services: docker

env:
  - DOCKER_COMPOSE_VERSION=1.17.1

before_install:
  - sudo apt-get update
  - sudo apt-get install -y expect jq

install:
  # Install Docker Compose
  - curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o "$HOME/bin/docker-compose"
  - chmod +x "$HOME/bin/docker-compose"
  - docker-compose --version

before_script:
  # Check docker & docker-compose versions
  - docker --version
  - docker-compose --version
  
  # Build images
  - docker-compose build

script:
  - docker-compose up -d

  # Verifications
  - sleep 4m
  - docker-compose logs
  - curl --retry 10 --retry-delay 5 -v http://localhost:9200/
  - curl --retry 10 --retry-delay 5 -v http://localhost:5601/
