FROM docker.elastic.co/kibana/kibana:5.6.3

LABEL maintainer "Elastic Docker Team https://github.com/elastic/kibana-docker"

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
