ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/kibana/kibana:${ELK_VERSION}

LABEL maintainer "Elastic Docker Team https://github.com/elastic/kibana-docker"

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
