version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Start date
          command: date
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-$(uname -s)-$(uname -m) > /tmp/docker-compose
            sudo mv /tmp/docker-compose /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Check versions
          command: |
            set -x
            docker --version
            docker-compose --version
      - run:
          name: Building containers
          command: docker-compose build
      - run:
          name: Starting containers
          command: docker-compose up -d
      - run:
          name: Check connection
          command: |
            set -x
            sleep 4m
            docker-compose logs
            curl --retry 10 --retry-delay 5 -v http://localhost:9200/
            curl --retry 10 --retry-delay 5 -v http://localhost:5601/
      - store_artifacts:
          path: /code/test-results
          destination: prefix
      - run:
          name: End date
          command: date
#https://circleci.com/docs/2.0/docker-compose/
#https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
