# uses ONBUILD instructions described here:
# https://github.com/gliderlabs/logspout/tree/master/custom

FROM gliderlabs/logspout:master
ENV SYSLOG_FORMAT rfc3164

LABEL maintainer "Elastic Docker Team <docker@elastic.co>"