ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}

LABEL maintainer "Elastic Docker Team https://github.com/elastic/elasticsearch-docker"

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
