# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:5.6.3

LABEL maintainer "Elastic Docker Team <docker@elastic.co>"

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
