ARG ELK_VERSION

FROM docker.elastic.co/logstash/logstash:${ELK_VERSION}

LABEL maintainer "Elastic Docker Team https://github.com/elastic/logstash-docker"

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
